import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import Layout from "@/Components/Layout";
import { assets } from "@/assets/assets.js";
import AnimatedText from "@/Components/AnimatedText";
import Link from "next/link";
import SaveAltIcon from '@mui/icons-material/SaveAlt';
import Hireme from "@/Components/Hireme";
import { motion } from "framer-motion";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const imageSlide = {
  initial: {
    opacity: 0,
    y: -50,
  },
  animate: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 1.5,
    },
  },
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Chinweike</title>
        <meta name="description" content="Generated by next app"/>
      </Head>

      <main className="flex items-center text-dark w-full min-h-screen dark:text-light ">
        <Layout className="pt-4">
          <div className="flex gap-10 items-center justify-between w-full">
            <motion.div className="w-1/3"
            variants={imageSlide}
              initial="initial"
              animate="animate"
            >
              <Image src={assets.profilepic} alt="chinweike" className="w-full h-auto rounded-[1.5rem]" priority sizes="(max-width: 760px) 100vw, (max-width: 1200px) 50vw, 50vw" />
              {/* priority increases the image loading speed. */}
            </motion.div>

            <div className="w-2/3 flex flex-col items-center self-center">
              {/* <h1>Turning Vision into Reality with code</h1> */}

              <AnimatedText text={"Turning Vision into Reality with code"} className="!text-left"/>
              <p className="my-4 text-base font-medium text-justify">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. 
              </p>

              <div className="flex gap-5 self-start items-center mt-2">
                <Link href="/resume" target="_blank"
                className="flex gap-2 items-center bg-dark text-light p-2 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark  dark:hover:border-light dark:hover:bg-dark dark:hover:text-light border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark"
                download={true}> Resume <SaveAltIcon /> </Link>

                <Link href={"/mailto:chinweiketwitter@gmail.com"} target="_blank"
                className="text-lg font-medium capitalize  underline"
                >Contact me..</Link>
                <Hireme />
              </div>
            </div>
          </div>
        </Layout>

        {/* <Hireme /> */}

      </main>
    </>
  );
}
